/*BASE CERO Datos &SOFT POSTGRES
@author Yaher Carrillo
@Date-Create 02/11/2018
@Desciption:
Elementos iniciales de las tablas maestro.
EJECUTAR COMO SE MUESTRA A CONTINUACION*/

/*SE CARGAN LOS IDIOMAS DE USO*/


INSERT INTO ISOFT_MIDIOMAS (COD_IDIOMA, NOMBRE_IDIOMA, HABILITADO) VALUES ('ES', 'ESPAÑOL', '1');
INSERT INTO ISOFT_MIDIOMAS (COD_IDIOMA, NOMBRE_IDIOMA, HABILITADO) VALUES ('EN', 'INGLES', '1');
INSERT INTO ISOFT_MIDIOMAS (COD_IDIOMA, NOMBRE_IDIOMA, HABILITADO) VALUES ('IT', 'ITALIANO', '1');

/*SE CARGAN LOS ESTILOS DE USO DE LA APLICACION*/
INSERT INTO ISOFT_MESTILOS (COD_ESTILO, NOMBRE_ESTILO, HABILITADO) VALUES ('ISOFT-BLACK', 'ESTILO OSCURO', '1');
INSERT INTO ISOFT_MESTILOS (COD_ESTILO, NOMBRE_ESTILO, HABILITADO) VALUES ('ISOFT-GRAY', 'ESTILO GRIS', '1');
INSERT INTO ISOFT_MESTILOS (COD_ESTILO, NOMBRE_ESTILO, HABILITADO) VALUES ('ISOFT-LIGTH', 'ESTILO BLANCO', '1');

/*SE CARGAN LOS ESTILOS DE USO DE LA APLICACION*/
INSERT INTO ISOFT_MCANALES (COD_CANAL, NOMBRE_CANAL, HABILITADO) VALUES ('APP-AN', 'ANDROID', '1');
INSERT INTO ISOFT_MCANALES (COD_CANAL, NOMBRE_CANAL, HABILITADO) VALUES ('APP-IOS', 'IOS', '1');
INSERT INTO ISOFT_MCANALES (COD_CANAL, NOMBRE_CANAL, HABILITADO) VALUES ('WEB', 'WEB', '1');
INSERT INTO ISOFT_MCANALES (COD_CANAL, NOMBRE_CANAL, HABILITADO) VALUES ('WEB-SERVICE', 'SERVICIO WEB', '1');

INSERT INTO ISOFT_MEVENTOS (COD_EVENTO,NOMBRE_EVENTO,HABILITADO) VALUES ('crear.usuarios', 'CREAR_USUARIOS', '1');
INSERT INTO ISOFT_MEVENTOS (COD_EVENTO,NOMBRE_EVENTO,HABILITADO) VALUES ('crear.usuarios.masivos', 'CREAR_USUARIOS_MASIVOS', '1');
INSERT INTO ISOFT_MEVENTOS (COD_EVENTO,NOMBRE_EVENTO,HABILITADO) VALUES ('asociar.perfil', 'ASOCIAR_PERFIL', '1');
INSERT INTO ISOFT_MEVENTOS (COD_EVENTO,NOMBRE_EVENTO,HABILITADO) VALUES ('desasociar.perfil', 'DESASOCIAR_PERFIL', '1');
INSERT INTO ISOFT_MEVENTOS (COD_EVENTO,NOMBRE_EVENTO,HABILITADO) VALUES ('consultar.perfiles', 'CONSULTAR_PERFILES', '1');
INSERT INTO ISOFT_MEVENTOS (COD_EVENTO,NOMBRE_EVENTO,HABILITADO) VALUES ('consultar.perfiles.usuario', 'CONSULTAR_PERFILES_USUARIO', '1');
INSERT INTO ISOFT_MEVENTOS (COD_EVENTO,NOMBRE_EVENTO,HABILITADO) VALUES ('administrar.status.usuarios', 'ADMIN_STATUS_USUARIOS', '1');




/*Se crea el perfil administrador*/
INSERT INTO ISOFT_PERFILES (NOMBRE_PERFIL, ADMINISTRADOR, HABILITADO) VALUES ('ADMINISTRADOR', '1', '1');
INSERT INTO ISOFT_PERFILES (NOMBRE_PERFIL, ADMINISTRADOR, HABILITADO) VALUES ('COORDINADOR', '0', '1');
INSERT INTO ISOFT_PERFILES (NOMBRE_PERFIL, ADMINISTRADOR, HABILITADO) VALUES ('SUPERVISOR', '0', '1');
INSERT INTO ISOFT_PERFILES (NOMBRE_PERFIL, ADMINISTRADOR, HABILITADO) VALUES ('GUEST', '0', '1');

/* Se agrega el parametro de administracion de clientes*/

INSERT INTO ISOFT_PARAMETROS (ID_PARAMETRO, DESCRIPCION, VALOR, TIPO_DATO, NOMBRE, GRUPO) VALUES ('1', 'Parametro que define el servicio a prestar', 'SERVICIO_NNITA', 'string', 'SERVICIO_CLIENTE', 'Administracion');

/* Se crea el usuario adminitrador */
INSERT INTO ISOFT_USUARIOS (ID_USUARIO, LOGIN, CLAVE, NOMBRE_USUARIO, APELLIDO_USUARIO, FECHA_REGISTRO, FECHA_ULTIMA_VIS, HABILITADO) VALUES ('24', 'ISOFT', '$2a$10$owUxR3ZFS.pg51BypTJDReew8hUcjYGGj24Otd6AAyOyR2oL5sEeW', 'ISOFT', 'ISOFT', '2018-07-13', '2018-07-13', '1');

/* Se asocia el usuario administrador a su perfil de acceso*/

INSERT INTO ISOFT_USUARIO_PERFIL (ID_USUARIO_PERFIL, ID_USUARIO, ID_PERFIL, HABILITADO) VALUES ('1', '24', '1', '1');

/* Se crean los menús de navegacion */
INSERT INTO ISOFT_MENU (ID_MENU, MENU_LABEL, ORDEN, REF_SECURITY,  HABILITADO) VALUES ('1', 'Inicio', '1', 'welcome', '1');

INSERT INTO ISOFT_MENU (ID_MENU, MENU_LABEL, ORDEN, REF_SECURITY, HABILITADO) VALUES ('2', 'Perfil Usuario', '2', 'profile_user', '1');
INSERT INTO ISOFT_MENU_ITEM (ID_MENU_ITEM, MENU_LINK, MENU_LABEL, ID_MENU_PADRE,ID_MENU_HIJO, ORDEN, REF_SECURITY, HABILITADO) VALUES ('1', '1', 'Registro de Actividad', '2','1', '1', 'bitacora_usuario', '1');
