/*BASE CERO &SOFT MYSQL
@author Yaher Carrillo
@Date-Create 21/05/2018
@Date-last-change 22/05/2018
@Desciption:
EJECUTAR COMO SE MUESTRA A CONTINUACION*/

/*Crear base de datos*/
CREATE DATABASE isoftnnita COLLATE 'utf8_general_ci';
/*Se toma la base de datos*/
use isoftnnita;

/**Tablas maestro**/

/*Tabla Maestro de Monedas sobre la aplicacion */
CREATE TABLE isoft_mmonedas (
	ID_MONEDA BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'identificador unico de la tabla maestro monedas',	
	COD_MONEDA  VARCHAR(20) NOT NULL COLLATE 'utf8_general_ci' COMMENT 'identificador de acceso comun de la tabla, llave primaria',
	NOMBRE_MONEDA  VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci' COMMENT 'nombre descriptivo del item',		
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'logico que habilita / deshabilita el registro val: 0,1',		
	PRIMARY KEY (COD_MONEDA),
	UNIQUE INDEX ID_MONEDA (ID_MONEDA)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;

/*Tabla Maestro de Idiomas sobre la aplicacion */
CREATE TABLE isoft_midiomas (
	ID_IDIOMA BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'identificador unico de la tabla maestro idiomas',	
	COD_IDIOMA  VARCHAR(20) NOT NULL COLLATE 'utf8_general_ci' COMMENT 'identificador de acceso comun de la tabla, llave primaria',
	NOMBRE_IDIOMA  VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci' COMMENT 'nombre descriptivo del item',		
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'logico que habilita / deshabilita el registro val: 0,1',		
	PRIMARY KEY (COD_IDIOMA),
	UNIQUE INDEX ID_IDIOMA (ID_IDIOMA)	
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;

/*Tabla Maestro de Estilos sobre la aplicacion */
CREATE TABLE isoft_mestilos (
	ID_ESTILO BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'identificador unico de la tabla maestro estilos',	
	COD_ESTILO  VARCHAR(20) NOT NULL COLLATE 'utf8_general_ci' COMMENT 'identificador de acceso comun de la tabla, llave primaria',
	NOMBRE_ESTILO  VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci'  COMMENT 'nombre descriptivo del item',		
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'logico que habilita / deshabilita el registro val: 0,1',		
	PRIMARY KEY (COD_ESTILO),
	UNIQUE INDEX ID_ESTILO (ID_ESTILO)		
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;


/*Tabla Maestro de Eventos sobre la aplicacion */
CREATE TABLE isoft_meventos (
	ID_EVENTO BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'identificador unico de la tabla maestro eventos',	
	COD_EVENTO  VARCHAR(20) NOT NULL COLLATE 'utf8_general_ci' COMMENT 'identificador de acceso comun de la tabla, llave primaria',
	NOMBRE_EVENTO  VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci' COMMENT 'nombre descriptivo del item',		
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'logico que habilita / deshabilita el registro val: 0,1',		
	PRIMARY KEY (COD_EVENTO),
	UNIQUE INDEX ID_EVENTO (ID_EVENTO)		
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;

/*Tabla Maestro de Canales de la aplicacion */
CREATE TABLE isoft_mcanales (
	ID_CANAL BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,	
	COD_CANAL  VARCHAR(20) NOT NULL COLLATE 'utf8_general_ci',
	NOMBRE_CANAL  VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',		
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0,		
	PRIMARY KEY (COD_CANAL),
	UNIQUE INDEX ID_CANAL (ID_CANAL)	
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;

/*Tabla Maestro de Paises de la aplicacion */
CREATE TABLE isoft_mpaises (
	ID_PAIS BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,	
	COD_PAIS  VARCHAR(20) NOT NULL COLLATE 'utf8_general_ci',
	NOMBRE_PAIS  VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',		
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0,		
	PRIMARY KEY (COD_PAIS),
	UNIQUE INDEX ID_PAIS (ID_PAIS)	
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;

/*Tabla Maestro de Bancos de la aplicacion */
CREATE TABLE isoft_mbancos (
	ID_BANCO BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,	
	ID_PAIS BIGINT(20) UNSIGNED NOT NULL,	
	COD_BANCO  VARCHAR(20) NOT NULL COLLATE 'utf8_general_ci',
	NOMBRE_BANCO  VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',		
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0,		
	PRIMARY KEY (COD_BANCO),
	UNIQUE INDEX ID_BANCO (ID_BANCO),
    INDEX UK_PAIS (ID_PAIS),
	CONSTRAINT FK_BANCO_PAIS FOREIGN KEY (ID_PAIS) REFERENCES isoft_mpaises (ID_PAIS)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;

/*Tabla Maestro de Tipos de Pagos que soporta la aplicacion */
CREATE TABLE isoft_mtipos_pagos (
	ID_TIPO_PAGO BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,	
	COD_TIPO_PAGO  VARCHAR(20) NOT NULL COLLATE 'utf8_general_ci',
	NOMBRE_TIPO_PAGO  VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',		
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0,		
	PRIMARY KEY (ID_TIPO_PAGO)	
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;

/*Tabla de Perfiles del sistema.*/
CREATE TABLE isoft_perfiles (
	ID_PERFIL BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	NOMBRE_PERFIL VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',	
	ADMINISTRADOR TINYINT(1) NOT NULL DEFAULT 0,	
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0,	
	PRIMARY KEY (NOMBRE_PERFIL),
	UNIQUE INDEX ID_PERFIL (ID_PERFIL)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;

COMMIT;

/*Tabla de Usuarios del sistema.*/
CREATE TABLE isoft_usuarios (
	ID_USUARIO BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	LOGIN VARCHAR(30) NOT NULL COLLATE 'utf8_general_ci',
	CLAVE VARCHAR(256) NOT NULL COLLATE 'utf8_general_ci',
	NOMBRE_USUARIO VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',
	APELLIDO_USUARIO VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',
	EMAIL VARCHAR(30) COLLATE 'utf8_general_ci',
	SEXO VARCHAR(1) COLLATE 'utf8_general_ci',
	FECHA_REGISTRO DATE NOT NULL, 
	FECHA_ULTIMA_VIS DATE , 
	PERFIL_DEFAULT BIGINT(20) UNSIGNED , 
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0,	
	PRIMARY KEY (ID_USUARIO),
	UNIQUE INDEX ID_USUARIO (ID_USUARIO),
	UNIQUE INDEX UK_LOGIN (LOGIN),
	UNIQUE INDEX UK_EMAIL (EMAIL),
	INDEX UDX_SEXO (SEXO),
	INDEX UDX_PERFIL_DEFAULT (PERFIL_DEFAULT),
	FOREIGN KEY (PERFIL_DEFAULT)
      REFERENCES isoft_perfiles(ID_PERFIL)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;



/*Tabla de parametros del sistema*/
CREATE TABLE isoft_usuario_perfil (
	ID_USUARIO_PERFIL BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,	
	ID_USUARIO  BIGINT(20) UNSIGNED NOT NULL ,		
	ID_PERFIL  BIGINT(20) UNSIGNED NOT NULL ,		
	HABILITADO INT NOT NULL ,	
	PRIMARY KEY (ID_USUARIO_PERFIL),	
	UNIQUE INDEX ID_PERFIL (ID_PERFIL),	      
   FOREIGN KEY (ID_PERFIL)
      REFERENCES isoft_perfiles(ID_PERFIL),
   FOREIGN KEY (ID_USUARIO)
      REFERENCES isoft_usuarios(ID_USUARIO)

)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;


/*Tabla de Menues principales del sistema.*/
CREATE TABLE isoft_menu (
	ID_MENU BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,	
	MENU_LABEL VARCHAR(30) NOT NULL COLLATE 'utf8_general_ci',		
	ORDEN INT(20),
	REF_SECURITY VARCHAR(220) COLLATE 'utf8_general_ci',
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0,	
	PRIMARY KEY (ID_MENU)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;

/*Tabla de Items de menu disponibles.*/
CREATE TABLE isoft_menu_item (
	ID_MENU_ITEM BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	MENU_LINK VARCHAR(120) NOT NULL COLLATE 'utf8_general_ci',	
	MENU_LABEL VARCHAR(30) NOT NULL COLLATE 'utf8_general_ci',	
	ID_MENU_PADRE BIGINT(20) UNSIGNED,
	ID_MENU_HIJO BIGINT(20),
	ORDEN INT(20),
	REF_SECURITY VARCHAR(220) COLLATE 'utf8_general_ci',
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0,	
	PRIMARY KEY (ID_MENU_ITEM),
	UNIQUE INDEX ID_MENU_ITEM (ID_MENU_ITEM),	
	INDEX IDX_MENU_ITEM_PADRE (ID_MENU_PADRE),	
	INDEX IDX_MENU_ITEM_HIJO (ID_MENU_HIJO),
	CONSTRAINT FK_MENU_PADRE_MENU FOREIGN KEY (ID_MENU_PADRE) REFERENCES isoft_menu (ID_MENU)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;



CREATE TABLE isoft_menus_perfil (
	ID_MENU_PERFIL BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,	
	ID_MENU  BIGINT(20) UNSIGNED NULL DEFAULT NULL,
	ID_PERFIL  BIGINT(20) UNSIGNED NULL DEFAULT NULL,	
	PRIMARY KEY (ID_MENU_PERFIL),
	UNIQUE INDEX ID_MENU_PERFIL (ID_MENU_PERFIL),
	INDEX IDX_MENU_PERFILES_MENU (ID_MENU),
	INDEX IDX_MENUS_PERFILES_PERFIL (ID_PERFIL),
	CONSTRAINT FK_MENU_PERFIL_MENU FOREIGN KEY (ID_MENU) REFERENCES isoft_menu (ID_MENU),
	CONSTRAINT FK_MENU_PERFIL_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES isoft_perfiles (ID_PERFIL)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;

/*Relacional de permisos de accion sobre perfiles*/
CREATE TABLE isoft_permisos (
	ID_PERMISO BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,	
	ID_MENU_ITEM  BIGINT(20) UNSIGNED NULL DEFAULT NULL,
	ID_PERFIL  BIGINT(20) UNSIGNED NULL DEFAULT NULL,	
	PRIMARY KEY (ID_PERMISO),
	UNIQUE INDEX ID_PERMISO (ID_PERMISO),
	INDEX IDX_PERM_MENU_ITEM (ID_MENU_ITEM),
	INDEX IDX_PERM_PERFILES (ID_PERFIL),
	CONSTRAINT FK_PERM_MENU_ITEM FOREIGN KEY (ID_MENU_ITEM) REFERENCES isoft_menu_item (ID_MENU_ITEM),
	CONSTRAINT FK_PERM_PERF FOREIGN KEY (ID_PERFIL) REFERENCES isoft_perfiles (ID_PERFIL)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;


/*Tabla Maestro de Eventos sobre la aplicacion */
CREATE TABLE isoft_bitacora (
	ID_BITACORA BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,	
	ID_EVENTO  BIGINT(20) UNSIGNED NOT NULL,
	ID_CANAL  BIGINT(20) UNSIGNED NOT NULL,		
	ID_USUARIO  BIGINT(20) UNSIGNED NOT NULL,			
	FECHA_REGISTRO  DATETIME NULL DEFAULT NULL,
	FECHA_REGISTRO_SEGUNDOS BIGINT(20) NULL DEFAULT NULL,
	IP  VARCHAR(20) COLLATE 'utf8_general_ci',		
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0,		
	PRIMARY KEY (ID_BITACORA),
	UNIQUE INDEX ID_BITACORA (ID_BITACORA),
	INDEX IDX_MAES_BIT_EVE (ID_EVENTO),		
	INDEX IDX_MAES_BIT_CANAL (ID_CANAL),	
	INDEX IDX_MAES_BIT_USUARIOS (ID_USUARIO),	
	CONSTRAINT FK_MAES_BIT_EVENT FOREIGN KEY (ID_EVENTO) REFERENCES isoft_meventos (ID_EVENTO),	
	CONSTRAINT FK_MAES_BIT_CANAL FOREIGN KEY (ID_CANAL) REFERENCES isoft_mcanales (ID_CANAL),
	CONSTRAINT FK_MAES_BIT_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES isoft_usuarios (ID_USUARIO)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;

/*Tabla Detalle de Eventos sobre la aplicacion */
CREATE TABLE isoft_detalle_bitacora (
	ID_DETALLE_BITACORA BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,	
	ID_BITACORA  BIGINT(20) UNSIGNED NOT NULL,	
	ID_EVENTO  BIGINT(20)  UNSIGNED NOT NULL,
	HORA_INICIO BIGINT(20) NULL DEFAULT NULL,
	HORA_FIN BIGINT(20) NULL DEFAULT NULL,
	DETALLE_VALOR_INICIO  VARCHAR(260) COLLATE 'utf8_general_ci',		
	DETALLE_VALOR_FIN  VARCHAR(260) COLLATE 'utf8_general_ci',		
	DESCRIPCION  VARCHAR(50) COLLATE 'utf8_general_ci',		
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0,		
	PRIMARY KEY (ID_DETALLE_BITACORA),
	UNIQUE INDEX ID_DETALLE_BITACORA (ID_DETALLE_BITACORA),
	INDEX IDX_DET_MAES_BITACORA (ID_BITACORA),	
	INDEX IDX_DET_BIT_EVENTOS (ID_EVENTO),	
	CONSTRAINT FK_DET_MAES_BITACORA FOREIGN KEY (ID_BITACORA) REFERENCES isoft_bitacora (ID_BITACORA),
	CONSTRAINT FK_DET_BIT_EVENTOS FOREIGN KEY (ID_EVENTO) REFERENCES isoft_meventos (ID_EVENTO)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;




/*Tabla de Registro de pagos de cliente propietarios*/
CREATE TABLE isoft_pagos_cliente (
	ID_PAGO BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,	
	ID_BANCO  BIGINT(20) UNSIGNED NOT NULL,	
	ID_MONEDA  BIGINT(20)  UNSIGNED NOT NULL,
	MONTO BIGINT(20) NULL DEFAULT NULL,
	FECHA_REGISTRO  DATETIME NULL DEFAULT NULL,
	HORA_REGISTRO BIGINT(20) NULL DEFAULT NULL,	
	DESCRIPCION  VARCHAR(50) COLLATE 'utf8_general_ci',		
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0,		
	PRIMARY KEY (ID_PAGO),
	UNIQUE INDEX ID_PAGO (ID_PAGO),
	INDEX IDX_PAG_ID_BANCO (ID_BANCO),	
	INDEX IDX_PAG_ID_MONEDA (ID_MONEDA),	
	CONSTRAINT FK_PAG_MAES_BANCO FOREIGN KEY (ID_BANCO) REFERENCES isoft_mbancos (ID_BANCO),
	CONSTRAINT FK_PAG_MAES_MONEDA FOREIGN KEY (ID_MONEDA) REFERENCES isoft_mmonedas (ID_MONEDA)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;


/*Tabla de Detalles adjuntos de Registro de pagos de cliente propietarios*/
CREATE TABLE isoft_pagos_referencias (
	ID_PAGO_REF BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	ID_PAGO BIGINT(20) UNSIGNED NOT NULL,	
	IMAGEN LONGBLOB NOT NULL,
	RUTA_NOMBRE_ARCHIVO_IMAGEN VARCHAR(256) NOT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (ID_PAGO_REF),
	UNIQUE INDEX ID_PAGO_REF (ID_PAGO_REF),
	INDEX IDX_PAG_REF_PAGO (ID_PAGO),	
	CONSTRAINT FK_PAG_REF_PAGO FOREIGN KEY (ID_PAGO) REFERENCES isoft_pagos_cliente (ID_PAGO)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;
/*Tabla de parametros del sistema*/
CREATE TABLE isoft_parametros (
	ID_PARAMETRO BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	DESCRIPCION VARCHAR(256) NOT NULL COLLATE 'utf8_general_ci',
	VALOR VARCHAR(256) NOT NULL COLLATE 'utf8_general_ci',
	TIPO_DATO VARCHAR(64) NOT NULL COLLATE 'utf8_general_ci',
	NOMBRE VARCHAR(128) NOT NULL COLLATE 'utf8_general_ci',
	GRUPO VARCHAR(64) NOT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (ID_PARAMETRO),
	UNIQUE INDEX ID_PARAMETRO (ID_PARAMETRO),
	UNIQUE INDEX UK_NOMBRE_GRUPO (NOMBRE, GRUPO)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

commit;